### ISSUE TITLE
opus_get downloads *all* corpora with just the -s switch

### ISSUE THREAD

**Issue by dumitrescustefan** [Helsinki-NLP/OpusTools#31]
Hi, 

I'm trying to create a monolingual corpus by taking all the ``source`` language data for a particular language, in this case ``ro``. Here's how I'm trying to do it:

```
opus_get -s ro -p raw -q
```

I used this exact command a longer time ago and it only downloaded 'ro' corpora (as I expected). Now, it downloads everything; I'm seeing ``GNOME_latest_raw_sw.zip`` to ``CCMatrix_latest_raw_de.zip``. I ran this command yesterday evening, and now (~one day later) I got a nice **650GB** folder of zips and it's still going strong, almost finished all 74 GB of English Paracrawl even though it has nothing to do with "ro".

While it's easy for me to just delete all the non-"ro" files after everything finishes, it's a waste of bandwidth and time..
Or did the behavior change and I'm using the command wrongly?

Could you please advise?
Regards!

**Comment by miau1** [comment]
Hello, sorry for the delayed response. `opus_get` will look for available parallel corpora in all languages when given only a source languages because OpusTools is mainly meant for processing parallel corpora. However, now in version 1.3.0 you can also download preprocessing type `mono` using only a source language with `opus_get`. This will give you only the monolingual files for that single language.
